openapi: 3.1.0
info:
  title: vpc-lattice
  description: >-
    <p>Amazon VPC Lattice is a fully managed application networking service that
    you use to connect, secure, and monitor all of your services across multiple
    accounts and virtual private clouds (VPCs). Amazon VPC Lattice interconnects
    your microservices and legacy services within a logical boundary, so that
    you can discover and manage them more efficiently. For more information, see
    the <a href="https://docs.aws.amazon.com/vpc-lattice/latest/ug/">Amazon VPC
    Lattice User Guide</a> </p>
paths:
  /services/{serviceIdentifier}/listeners/{listenerIdentifier}/rules:
    GET:
      summary: Listrules
      description: Lists the rules for the listener.
      operationId: amazonWebServicesListRules
  /accesslogsubscriptions:
    GET:
      summary: Listaccesslogsubscriptions
      description: >-
        Lists all access log subscriptions for the specified service network or
        service.
      operationId: amazonWebServicesListAccessLogSubscriptions
  /services/{serviceIdentifier}/listeners:
    GET:
      summary: Listlisteners
      description: Lists the listeners for the specified service.
      operationId: amazonWebServicesListListeners
  /services:
    GET:
      summary: Listservices
      description: >-
        Lists the services owned by the caller account or shared with the caller
        account.
      operationId: amazonWebServicesListServices
  /servicenetworks:
    GET:
      summary: Listservicenetworks
      description: >-
        Lists the service networks owned by the caller account or shared with
        the caller account. Also includes the account ID in the ARN to show
        which account owns the service network.
      operationId: amazonWebServicesListServiceNetworks
  /servicenetworkserviceassociations:
    GET:
      summary: Listservicenetworkserviceassociations
      description: >-
        Lists the associations between the service network and the service. You
        can filter the list either by service or service network. You must
        provide either the service network identifier or the service identifier.
        Every association in Amazon VPC Lattice is given a unique Amazon
        Resource Name (ARN), such as when a service network is associated with a
        VPC or when a service is associated with a service network. If the
        association is for a resource that is shared with another account, the
        association will include the local account ID as the prefix in the ARN
        for each account the resource is shared with.
      operationId: amazonWebServicesListServiceNetworkServiceAssociations
  /servicenetworkvpcassociations:
    GET:
      summary: Listservicenetworkvpcassociations
      description: >-
        Lists the service network and VPC associations. You can filter the list
        either by VPC or service network. You must provide either the service
        network identifier or the VPC identifier.
      operationId: amazonWebServicesListServiceNetworkVpcAssociations
  /targetgroups:
    GET:
      summary: Listtargetgroups
      description: >-
        Lists your target groups. You can narrow your search by using the
        filters below in your request.
      operationId: amazonWebServicesListTargetGroups
  /accesslogsubscriptions/{accessLogSubscriptionIdentifier}:
    PATCH:
      summary: Updateaccesslogsubscription
      description: Updates the specified access log subscription.
      operationId: amazonWebServicesUpdateAccessLogSubscription
  /authpolicy/{resourceIdentifier}:
    PUT:
      summary: Putauthpolicy
      description: Creates or updates the auth policy.
      operationId: amazonWebServicesPutAuthPolicy
  /services/{serviceIdentifier}/listeners/{listenerIdentifier}:
    PATCH:
      summary: Updatelistener
      description: Updates the specified listener for the specified service.
      operationId: amazonWebServicesUpdateListener
  /resourcepolicy/{resourceArn}:
    PUT:
      summary: Putresourcepolicy
      description: >-
        Attaches a resource-based permission policy to a service or service
        network. The policy must contain the same actions and condition
        statements as the Amazon Web Services Resource Access Manager permission
        for sharing services and service networks.
      operationId: amazonWebServicesPutResourcePolicy
  /services/{serviceIdentifier}/listeners/{listenerIdentifier}/rules/{ruleIdentifier}:
    PATCH:
      summary: Updaterule
      description: >-
        Updates a rule for the listener. You can't modify a default listener
        rule. To modify a default listener rule, use UpdateListener.
      operationId: amazonWebServicesUpdateRule
  /services/{serviceIdentifier}:
    PATCH:
      summary: Updateservice
      description: Updates the specified service.
      operationId: amazonWebServicesUpdateService
  /servicenetworks/{serviceNetworkIdentifier}:
    PATCH:
      summary: Updateservicenetwork
      description: Updates the specified service network.
      operationId: amazonWebServicesUpdateServiceNetwork
  /servicenetworkserviceassociations/{serviceNetworkServiceAssociationIdentifier}:
    GET:
      summary: Getservicenetworkserviceassociation
      description: >-
        Retrieves information about the specified association between a service
        network and a service.
      operationId: amazonWebServicesGetServiceNetworkServiceAssociation
  /servicenetworkvpcassociations/{serviceNetworkVpcAssociationIdentifier}:
    PATCH:
      summary: Updateservicenetworkvpcassociation
      description: >-
        Updates the service network and VPC association. Once you add a security
        group, it cannot be removed.
      operationId: amazonWebServicesUpdateServiceNetworkVpcAssociation
  /targetgroups/{targetGroupIdentifier}:
    PATCH:
      summary: Updatetargetgroup
      description: Updates the specified target group.
      operationId: amazonWebServicesUpdateTargetGroup
  /targetgroups/{targetGroupIdentifier}/deregistertargets:
    POST:
      summary: Deregistertargets
      description: Deregisters the specified targets from the specified target group.
      operationId: amazonWebServicesDeregisterTargets
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes the specified tags from the specified resource.
      operationId: amazonWebServicesUntagResource
  /targetgroups/{targetGroupIdentifier}/listtargets:
    POST:
      summary: Listtargets
      description: >-
        Lists the targets for the target group. By default, all targets are
        included. You can use this API to check the health status of targets.
        You can also ï¬lter the results by target. 
      operationId: amazonWebServicesListTargets
  /targetgroups/{targetGroupIdentifier}/registertargets:
    POST:
      summary: Registertargets
      description: >-
        Registers the targets with the target group. If it's a Lambda target,
        you can only have one target in a target group.
      operationId: amazonWebServicesRegisterTargets
tags: []
